sudo: required
services:
  - docker

before_install:
  - docker build -t surajprogrammez/docker-react -f Dockerfile.dev .

script:
  - docker run --name=test-container surajprogrammez/docker-react npm run test -- --coverage